#!/usr/bin/ruby

usage = <<EOS
Usage: fdiff [-i] [file1] file2

Prints which lines in file2 do not exist in file 1 (or STDIN if file1 is not specified)
-i reverses the files and checks which lines in file1 (or STDIN) do not exist in file 2
-v does the inverse and checks which lines match.
EOS
  
files = ARGV.select {|a| ! a.start_with? '-' }

if files.length > 2 || files.length < 1 || (files.length < 2 && STDIN.tty?)
  puts usage
  exit 1
end

files.each do |f|
  unless File.exist? f
    puts "File does not exist: #{f}"
    exit 1
  end
end

invert_check = ARGV.include? '-v'
invert_files = ARGV.include? '-i'

def chomp(lines)
  lines.collect {|l| l.chomp}
end

def load(file)
  chomp File.readlines(file)
end

if files.length == 2
  input1 = load files[0]
  input2 = load files[1]
else
  input2 = load files[0]
  input1 = chomp STDIN.readlines
end

if invert_files
  list = input2
  lines = input1
else
  list = input1
  lines = input2
end



lines.each do |line|
  if list.include? line
    puts line if invert_check
  else
    puts line unless invert_check
  end
end
